export const SET_MUNE = 'SET_MUNE'
export const GET_MANTYPE = 'GET_MANTYPE' // 获取管理类
export const GET_FUNDINVESTMENT = 'GET_FUNDINVESTMENT' // 基金投向
export const GET_MANAGEMENTCOMPANY = 'GET_MANAGEMENTCOMPANY' // 管理公司
export const GET_ORGTYPE = 'GET_ORGTYPE' // 组织类型
export const GET_MYFUNDLIDT = 'GET_MYFUNDLIDT' // 获取我的基金
export const GET_MYFUNDDETAILS = 'GET_MYFUNDDETAILS' // 获取我的基金详情
export const GET_FUNDSTAGE = 'GET_FUNDSTAGE' // 基金阶段
export const GET_FUNDSTATUS = 'GET_FUNDSTATUS' // 基金状态
export const GET_ALLORGLIST = 'GET_ALLORGLIST' // 下拉获取所有的合作机构
